# FRONT E BACK DEVEM TER SEU PROPRIO DOCKERFILE

version: '3.8'
services:
  web:
    build: ./frontend
    container_name: web
    depends_on:
      - api
    restart: unless-stopped
    ports:
      - 80:3000
    volumes:
      - ./frontend:/app
  api:
    build: ./backend
    container_name: api
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: db
      DB_PORT: 3306
    volumes: 
      - ./backend:/app
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:                                                                                                              
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
